baseURL = "https://brentscott.us"
languageCode = "en-us"
theme = "aafu"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
staticDir = "static"
    
[params]
    title = "brentscott.us"
    author = "Brent Scott"
    description = "Personal website for Brent Scott"
    copyright = ""
    footer = "&copy; [Brent Scott](https://brentscott.us) 2022"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false 

    [params.favicons]
        use = true
        metas = '''
       <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
       <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
       <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
       <link rel="manifest" href="/site.webmanifest">
        '''

    # Profile section
    [params.profile]
    name = "Brent Scott, PhD, CSCS"
		tagline = "Postdoctoral Research Associate"
		location = "WashU"
    photo = "profile_brent.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"
        
        #[[params.social.list]]
          #  class = "fab"
           # icon = "fa-stack-overflow"
            #url = "https://stackoverflow.com/users/11437205/bs93?tab=profile"
            #title = "StackOverflow"
       # [[params.social.list]]
        #    class = "ai"
         #   icon = "fa-envelope"
          #  url = "bdscott@umass.edu"
           # title = "Email"
        [[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar" 
            url = "https://scholar.google.com/citations?hl=en&user=v_4YkmYAAAAJ&view_op=list_works&gmla=AJsN-F588qLiiHEzJJZucY6rIHVxxSNzkWmGYy-IhAN5k2z3H5MibxUAkczE1LAULACKyXMX2sEK9pS3TqvBTrSEpHO9Pkjt4e7Y_-i_s10GHrA6z9NW0ic"
            title = "Google Scholar"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/brentscott93"
            title = "GitHub"
        #[[params.social.list]]
         #   class = "fab"
          #  icon = "fa-twitter"
           # url = "https://twitter.com/brentscott93"
            #title = "Twitter"
	[[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "https://stackoverflow.com/users/11437205/bs93?tab=profile"
            title = "StackOverflow"
    [[params.social.list]]
            class = "fab"
            icon = "fa-strava"
            url = "https://www.strava.com/athletes/50701336"
            title = "Strava"	
		#[[params.social.list]]
         #   class = "ai"
         #   icon = "ai-researchgate"
          #  url = "#"
         #   title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "research"
    [[params.showInAccordion]]
        item = "teaching"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"
    [[params.showInAccordion]]
        item = "drums"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**I'm Brent.** Currently, I am a post-doc at Washington University in St. Louis in the department of Biochemistry & Molecular Biophysics studying studying in the [Greenberg lab.](https://glab.biochem.wustl.edu/) I use *in vitro* techniques to explore force generation in molecular motors and to characterize the molecular/biophsyical properties of cardiac muscle disfunction underlying heart disease. [My CV is here.](https://brentscott.us/cv.pdf)" 

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"
        
        [[params.education.list]]
            degree = "**Postdoctoral Research Associate**"
            college = "Washington Unversity in St. Louis"
            dates = "2022 - *Present*"

        [[params.education.list]]
            degree = "**Ph.D. in Kinesiology**"
            college = "University of Massachusetts Amherst"
            dates = "2019 - 2022"
            thesis_title = "What is the relative timing between myosin's powerstroke and phosphate release?"
            thesis_link = "https://brentscott.us/dissertation"

        [[params.education.list]]
            degree = "**M.S. in Kinesiology**"
            college = "University of Massachusetts Amherst"
            dates = "2016 - 2019"
            thesis_title = "Tropomyosin-Based Effects of Acidosis on Thin-Filament Regulation During Muscle Fatigue"
            thesis_link = "https://scholarworks.umass.edu/masters_theses_2/795/"

        [[params.education.list]]
            degree = "**B.S. in Exercise Science**"
            college = "Belmont University"
            dates = "2012 - 2016"

    # Research section
    [params.research]
        title = "Research"
        icon = "fas fa-microscope"

        [[params.research.list]]
            position = "**Postdoctoral Research Associate"
            dates = "2022 - *Present*"
            company = "Biochemistry & Mocular Biophysics (WashU)"
            details = "My current research interests involve characterizing the molecular determinents of genetic cardiomyopathies and related heart diseases. I also feel strongly about using/contributing to open source and reproducible science, software, and communities."


        [[params.research.list]]
            position = "**Graduate Research Assistant**"
            dates = "2016 - 2022"
            company = "Muscle Biophysics Lab (UMass Amherst)"
            details = "My research focus in grad school was in the field of single molecule biophysics. More specifically, my interests included investigating the molecular mechanisms underlying the regulation of force generation and energy transduction in skeletal muscle myosin II and its associated regulatory proteins, troponin and tropomyosin."

        [[params.research.list]]
            position = "**Undergraduate Research Assistant**"
            dates = "2015 - 2016"
            company = "Neuromuscular Physiology Lab (Vanderbilt University Medical Center)"
            details = ""


    # Teaching section
    [params.teaching]
        title = "Teaching"
        icon = "fas fa-book"

        [[params.teaching.list]]
            position = "**Courses Taught**"
            dates = "UMass Amherst"
            company = "KIN 110 (Human Performance & Nutrition); KIN 470 (Exercise Physiology)"

        [[params.teaching.list]]
            position = "**Graduate Teaching Assistant**"
            dates = "UMass Amherst"
            company = "KIN 100 (Introduction to Kinesiology); KIN 110; KIN 394 (Applied Exercise Testing)"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-newspaper"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]
 
   [[params.publication.list]]
            title = "Myosin's powerstroke occurs prior to the release of phosphate from the active site"
            authors = "Scott B, Marang C, Woodward M, & Debold EP"
            date = "2021"
            journal = "Cytoskeleton. https://doi.org/10.1002/cm.21682"
            link = "publications/scott-marang-2021-cytoskeleton.pdf"
            type = "Journal Articles"
            
    [[params.publication.list]]
            title = "FRET and optical trapping reveal mechanisms of actin-activation of the power stroke and phosphate-release in myosin V"
            authors = "Gunther LK, Rohde JA, Tang W, Cirilo JA Jr, Marang CP, Scott BD, Thomas DD, Debold EP, Yengo CM"
            date = "2020"
            journal = "J Biol Chem. doi: 10.1074/jbc.RA120.015632"
            link = "publications/gunther-2020-jbc.pdf"
            type = "Journal Articles"
            
    [[params.publication.list]]
            title = " Positional Isomers of a Non-Nucleoside Substrate Differentially Affect Myosin Function. "
            authors = "Mike Woodward, Eric Ostrander, Seung P. Jeong, Xiarong Liu, Brent Scott, Matt Unger, Jianhan Chen, Dhandapani Venkataraman, Edward P. Debold"
            date = "2020"
            journal = "Biophysical Journal 119(3), 567-580"
            link = "https://brentscott.us/publications/woodward-2020-skeletal-azo.pdf"
            type = "Journal Articles"

        #[[params.publication.list]]
         #   title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        #    authors = "F Last, F Second, P secondary"
        #    date = "2018"
        #    journal = "Journal of Field 52 (16), 9033-9044"
        #    link = "#"
         #   type = "Journal Articles"
        [[params.publication.list]]
            title = "Enhancing Cardiac Myosin Function with an Abiotic Energy Source"
            authors = "Mike K Woodward, Eric Ostrander, Brent D Scott, Christopher Marang, Xiaorong Liu, Jianhan Chen, Dhandapani Venkataraman, Edward P Debold"
            date = "2021"
            journal = "Biophysical Journal 120 (3), 249a"
            link = "https://www.cell.com/biophysj/pdf/S0006-3495(20)32529-7.pdf"
            type = "Proceedings"
            
		 [[params.publication.list]]
            title = "Tirasemtiv and dATP Synergistically Reverse the Acidosis-induced Depression of Myosinâ€™s Force and Motion Generating Capacity"
            authors = "Christopher P Marang, Brent D Scott, Mike K Woodward, Edward P Debold"
            date = "2021"
            journal = "Biophysical Journal 120 (3), 60a0"
            link = "https://www.cell.com/biophysj/pdf/S0006-3495(20)31505-8.pdf"
            type = "Proceedings"
            
        [[params.publication.list]]
            title = " Rapid Onset Vasodilation in the Leg is Greater in Habitual Endurance Runners."
            authors = "Coolbaugh C., Bush E., Sabin S., Scott B., Damon B., & Towse T."
            date = "2016"
            journal = "The FASEB Journal, 30(1 Supplement), 761.10-761.10"
            link = "https://www.fasebj.org/doi/abs/10.1096/fasebj.30.1_supplement.761.10"
            type = "Proceedings"
 
    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "lasertrapr"
            url = "https://lasertrapr.app"
            description = "Automated analysis of laser trap data using *R Shiny*"
    #    [[params.project.list]]
    #        title = "project"
     #       url = "#"
     #       description = "Description of the project"
     #   [[params.project.list]]
     #       title = "project"
      #      url = "#"
       #     description = "Description of the project"
       # [[params.project.list]]
         #   title = "project"
          #  url = "#"
           # description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Laser Trapping"
            skillrating = 90
        [[params.skill.list]]
            skill = "Data Analysis (R programming)"
            skillrating = 95
        [[params.skill.list]]
            skill = "In Vitro Motility"
            skillrating = 85

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Spending time with my wife and our kiddos"
        [[params.hobby.list]]		
		    hobby = "Running, biking, kayaking (really anything outdoorsy!)"
        [[params.hobby.list]]		
		    hobby = ""
		
		
		
		#Drums section
    [params.drums]
        title = "Alter-ego"
        icon = "fas fa-drum"
		
        [[params.drums.list]]		
		    drums = "Virtual drum lessons through [Naples Park Music](http://naplesparkmusic.rocks)"
